[build]
    # command = "npm run build"
    # publish = "/public"
    functions = "functions-build"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
    
[[headers]]
    for = "/*"
        [headers.values]
            Access-Control-Allow-Origin = "*"
